name: Build and Deploy CAP App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Verify CF CLI
        run: cf version


      - name: Login to CF
        run: |
          cf api https://api.cf.ap21.hana.ondemand.com
          cf auth rkkramesh2001@gmail.com Rkk_@2001

      - name: Install dependencies
        run: npm install

      # - name: Build CAP project
      #   run: npx cds build --production

      - name: Install MBT
        run: npm install -g mbt
      


      - name: Build MTA archive
        run: mbt build

      # Optional: Deploy to SAP BTP (Cloud Foundry)
      # Requires secrets configured in GitHub


      - name: Deploy MTA
        run: cf deploy mta_archives/*.mtar
